# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM-RxSwift-Subjects' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-RxSwift-Subjects
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Kingfisher', '~> 7.0'

  target 'MVVM-RxSwift-SubjectsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM-RxSwift-SubjectsUITests' do
    # Pods for testing
  end

end
